language: python
python:
- "2.7"
install:
- "pip install -r requirements.txt"
- "pip install -r tests/requirements.txt"
script:
- bash tests/runtest.sh
deploy:
  - provider: pypi
    #server: https://testpypi.python.org/pypi
    user: codeskyblue
    password:
      secure: tfJTs+uV5he1mTshNDea0RLOIMDYy+c3L8ASDczD2Mkx7C+nFegCssch/xbPgWmHwHXw2Tx4Kl10AAPYgZRA605aHqj1CmqEdQHVJ8JvHICXRvb9EqMLWFNTglFEDcAk2pARdmXh4fnSEjdsM3PBT21ZmuNm0Q4wDYAM/U/uEauNYvqGuhTcmS8+fSFal5Qmursq1ZJnem7G6pQvfoq0xj5OCF0LIEAk3P1m9QZ9djwh0/Naf5QXeRp9emS5b07sxJzqLwLrG98ElKFPMmAzEXV4YEeAvwPJK5PrwYYpv1a9pupljaHDd8v209GYX+ZH/Bx33MgptKQdZE8kG2PA/bgTz9AyNf1PLI4vOQ6UZoVsToEtP1jLpxnID7qUb+eZ0Lj+ioaNXHjP8sLgYrzB9xU13z+yP5lg7oYWg4wPdGlNtv3NRe+NFbzL1E/cDBe44Gxxz2ScFH6Cc5JRKDSRgwPsoFQllkjF6/LRflWDA8j75Cxxj1VdkCuMOJu6gBi6a2gfH10VEP2x95JlMuJtQx66Y6TUtzVMEr3p0dSljlqSsCEA3dsEYzcnpA3l5DIron88VePWWK6Hr7H2JivRP3rK4dWUWH9VAgt4Boz5Mh/oD5rf4B9BrWjdUmf/UaFvgEkzIipjxc31yXAbattTH0NBJfhFeYPrf/aZiISR6t8=
    distributions: sdist bdist_wheel
  - provider: pypi
    user: codeskyblue
    password:
      secure: gP+Fo/jBmk32PW2p01wSX/qL6rj6Y7X+ZZ1XLHKUXtBCwVQtAvYtqlevVIKuvima4DDjF4YYzZFN1XLGt3j10MRKKNHrn8pV7I90KqvLk2uodmBASn0HGnGRCEFyJDgkCJT9BqOXbfATcxtMt5yBpf1HRk9f4CQvW3yuKfqd8kSyUnDYN7xHQBAxqYrlihW6jZ0yb38fx8WNvmjRxNknoUsr9m8qO7vfkbAaff+AwBG39UTOFrGpRk909/BVLze69vEyupJurNQDN01MP7IumwbCaG2wYTqC8T1OYm4huBQqhI+AhG2fkznAS2FEL/3NGDLZGjPfsozEnyahwt6NQl6idBumBlSaZcFoO0ulROa1yVEuBA8ODgk9zH9pADcuo3Yg7fgkHZ0FNwrqEBbEEG0c8q6rv3a/aBFDVXTTmvKLUMS83bkafMuMGCH+pm5KBV6wD/Bq0PXjeY6PXo9ucPQFWCeaIsWPsaYso668aYMSqStbaoReg4iDgC95uNHBnba59SbMWj3ASW/1nmsgaXYzov1H2lIEMuS0OO5h+gtC/ft+Alja/qVhEUN9+SpQz5St9KHfMBsIw/O9hucCx/egsmge9Wxdr18fTlesGDUs3Quco5vZwJuscutf1dHTylwORwQKJztnRoyQoHY6v5lMqbmoI/xs72H6mcCaHlk=
    distributions: sdist bdist_wheel
    on:
      tags: true
after_deploy:
  - "curl -X POST https://readthedocs.org/build/atx"
